### ISSUE TITLE
New Line problem

### ISSUE THREAD

**Issue by CosmaVito** [evilstreak/markdown-js#283]
Hi in bootstrap markdown new line inside paragraph not work. I use **markdown-js** to obtein marked text.
![immagine](https://cloud.githubusercontent.com/assets/14861632/21304787/d3ef832a-c5c7-11e6-8370-f180ef685f2f.png)

Instead if i put two spaces after the new line i have the correct result...
![immagine](https://cloud.githubusercontent.com/assets/14861632/21304792/d8c393b4-c5c7-11e6-8392-402590e41cf5.png)

why this strange behavior??

Has anyone found a solution?Thanks :)

**Comment by kpcyrd** [comment]
This is the correct way as described in the original markdown docs. :)

github uses a [github flavored markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown), I'm currently looking for a way to enable the github linebreaking-way as well.

**Comment by ashb** [comment]
In the default Gruber dialect this can be achieved by having two trailing spaces on the end of the line. https://github.com/evilstreak/markdown-js/blob/master/test/features/linebreaks/simple.text -- i.e. 
```
Line1  ¶
Line2¶
```

(where `¶` represents a new line. Otherwise it's a bit hard to see where the spaces are.)

I made a start of Github's flavor in the `gfm` branch but didn't finish it or need it in the end.
